# basic options
title: REEL
author: ReelMaster
email: reelmaster@gmail.com
description: Robots in Education &Entertaiment Lab
twitter_username: reelmaster
github_username:  reelmaster

url: "https://reelmaster.github.io"
baseurl: "REEL-Blog"

# use a logo image in your nav bar.
use_logo: true

# logo image to use. logo images are constrained at 50px in height.
logo: "http://reel.hansung.ac.kr/reel/img/maintop.png"

# use text title instead. text title read from uistring.title in ui strings section.
use_text_title: false

cover: "http://reel.hansung.ac.kr/reel/img/mainlogo.png"

# Build settings
markdown: kramdown
theme: minima



