# basic options
title: REEL
author: ReelMaster
email: reelmaster@gmail.com
description: Robots in Education &Entertaiment Lab
twitter_username: reelmaster
github_username:  reelmaster

url: "https://reelmaster.github.io"
baseurl: "REEL-Blog"

# Build settings
markdown: kramdown
theme: minima



